/** Sector tags for NSE universe symbols — used by Sector Scope. */
export const SECTOR_BY_SYMBOL: Record<string, string> = {
  RELIANCE: "Energy",
  ONGC: "Energy",
  BPCL: "Energy",
  IOC: "Energy",
  GAIL: "Energy",
  PETRONET: "Energy",
  IGL: "Energy",
  MGL: "Energy",
  ATGL: "Energy",
  OIL: "Energy",

  TCS: "IT",
  INFY: "IT",
  HCLTECH: "IT",
  WIPRO: "IT",
  TECHM: "IT",
  LTIM: "IT",
  PERSISTENT: "IT",
  COFORGE: "IT",
  MPHASIS: "IT",
  OFSS: "IT",

  HDFCBANK: "Banking",
  ICICIBANK: "Banking",
  SBIN: "Banking",
  AXISBANK: "Banking",
  KOTAKBANK: "Banking",
  INDUSINDBK: "Banking",
  BANKBARODA: "Banking",
  PNB: "Banking",
  CANBK: "Banking",
  UNIONBANK: "Banking",
  IDFCFIRSTB: "Banking",
  FEDERALBNK: "Banking",

  BAJFINANCE: "Financials",
  BAJAJFINSV: "Financials",
  HDFCLIFE: "Financials",
  SBILIFE: "Financials",
  LICI: "Financials",
  SBICARD: "Financials",
  CHOLAFIN: "Financials",
  MUTHOOTFIN: "Financials",
  MANAPPURAM: "Financials",
  ICICIGI: "Financials",
  ICICIPRULI: "Financials",
  SHRIRAMFIN: "Financials",
  BAJAJHLDNG: "Financials",
  HDFCAMC: "Financials",
  "NAM-INDIA": "Financials",
  ANGELONE: "Financials",
  IIFL: "Financials",
  MOTILALOFS: "Financials",
  BSE: "Financials",
  MCX: "Financials",
  CDSL: "Financials",
  CAMS: "Financials",
  PAYTM: "Financials",
  POLICYBZR: "Financials",

  BHARTIARTL: "Telecom",

  ITC: "FMCG",
  HINDUNILVR: "FMCG",
  NESTLEIND: "FMCG",
  BRITANNIA: "FMCG",
  DABUR: "FMCG",
  MARICO: "FMCG",
  GODREJCP: "FMCG",
  COLPAL: "FMCG",
  TATACONSUM: "FMCG",
  VBL: "FMCG",
  "MCDOWELL-N": "FMCG",
  UBL: "FMCG",
  RADICO: "FMCG",

  LT: "Capital Goods",
  SIEMENS: "Capital Goods",
  ABB: "Capital Goods",
  BEL: "Capital Goods",
  HAL: "Capital Goods",
  BHEL: "Capital Goods",
  CUMMINSIND: "Capital Goods",
  HAVELLS: "Capital Goods",
  VOLTAS: "Capital Goods",
  POLYCAB: "Capital Goods",
  KEI: "Capital Goods",
  DIXON: "Capital Goods",
  ASTRAL: "Capital Goods",
  SUPREMEIND: "Capital Goods",
  MAZDOCK: "Capital Goods",
  COCHINSHIP: "Capital Goods",
  GRSE: "Capital Goods",

  MARUTI: "Auto",
  "M&M": "Auto",
  TATAMOTORS: "Auto",
  EICHERMOT: "Auto",
  HEROMOTOCO: "Auto",
  "BAJAJ-AUTO": "Auto",
  TVSMOTOR: "Auto",
  MOTHERSON: "Auto",
  BOSCHLTD: "Auto",
  MRF: "Auto",
  BALKRISIND: "Auto",
  APOLLOTYRE: "Auto",
  EXIDEIND: "Auto",
  AMARAJABAT: "Auto",
  ASHOKLEY: "Auto",
  ESCORTS: "Auto",
  TIINDIA: "Auto",

  SUNPHARMA: "Pharma",
  CIPLA: "Pharma",
  DRREDDY: "Pharma",
  DIVISLAB: "Pharma",
  AUROPHARMA: "Pharma",
  LUPIN: "Pharma",
  TORNTPHARM: "Pharma",
  BIOCON: "Pharma",
  ZYDUSLIFE: "Pharma",
  ALKEM: "Pharma",
  LAURUSLABS: "Pharma",
  GLENMARK: "Pharma",
  IPCALAB: "Pharma",
  ABBOTINDIA: "Pharma",
  SYNGENE: "Pharma",

  APOLLOHOSP: "Healthcare",
  MAXHEALTH: "Healthcare",
  FORTIS: "Healthcare",
  METROPOLIS: "Healthcare",
  LALPATHLAB: "Healthcare",

  NTPC: "Power",
  POWERGRID: "Power",
  ADANIPOWER: "Power",
  TATAPOWER: "Power",
  TORNTPOWER: "Power",
  NHPC: "Power",
  SJVN: "Power",
  COALINDIA: "Power",

  ULTRACEMCO: "Cement",
  GRASIM: "Cement",
  AMBUJACEM: "Cement",
  SHREECEM: "Cement",
  ACC: "Cement",
  DALBHARAT: "Cement",
  RAMCOCEM: "Cement",

  TATASTEEL: "Metals",
  JSWSTEEL: "Metals",
  HINDALCO: "Metals",
  VEDL: "Metals",
  JINDALSTEL: "Metals",
  NMDC: "Metals",
  SAIL: "Metals",
  NATIONALUM: "Metals",
  HINDCOPPER: "Metals",

  ADANIENT: "Conglomerate",
  ADANIPORTS: "Infrastructure",
  CONCOR: "Infrastructure",
  IRCTC: "Infrastructure",
  IRFC: "Infrastructure",
  PFC: "Infrastructure",
  RECLTD: "Infrastructure",
  INDIGO: "Aviation",
  DELHIVERY: "Logistics",

  DLF: "Realty",
  GODREJPROP: "Realty",
  LODHA: "Realty",

  TITAN: "Consumer",
  TRENT: "Consumer",
  DMART: "Consumer",
  NYKAA: "Consumer",
  ZOMATO: "Consumer",
  PAGEIND: "Consumer",
  KALYANKJIL: "Consumer",
  ASIANPAINT: "Consumer",
  BERGEPAINT: "Consumer",
  PIDILITIND: "Chemicals",
  SRF: "Chemicals",
  PIIND: "Chemicals",
  DEEPAKNTR: "Chemicals",

  INDHOTEL: "Hospitality",
  IHCL: "Hospitality",
  JUBLFOOD: "Hospitality",
  DEVYANI: "Hospitality",

  NAUKRI: "Media",
};

export function getSector(symbol: string): string {
  return SECTOR_BY_SYMBOL[symbol] ?? "Others";
}

/** Yahoo symbols for sector / thematic index heat. */
export const SECTOR_INDEX_QUOTES = [
  { yahoo: "^NSEI", name: "Nifty 50", sector: "Benchmark" },
  { yahoo: "^NSEBANK", name: "Nifty Bank", sector: "Banking" },
  { yahoo: "^CNXIT", name: "Nifty IT", sector: "IT" },
  { yahoo: "^CNXAUTO", name: "Nifty Auto", sector: "Auto" },
  { yahoo: "^CNXPHARMA", name: "Nifty Pharma", sector: "Pharma" },
  { yahoo: "^CNXMETAL", name: "Nifty Metal", sector: "Metals" },
  { yahoo: "^CNXFMCG", name: "Nifty FMCG", sector: "FMCG" },
  { yahoo: "^CNXENERGY", name: "Nifty Energy", sector: "Energy" },
  { yahoo: "^CNXINFRA", name: "Nifty Infra", sector: "Infrastructure" },
  { yahoo: "^CNXREALTY", name: "Nifty Realty", sector: "Realty" },
] as const;
