/**
 * NSE-aligned sector buckets (Nifty sectoral groups).
 * Source: NSE India sectoral index taxonomy —
 * Automobile, Banking, Finance, IT, Healthcare, Consumer Goods,
 * Infrastructure & Construction, Energy, Industrial & Goods,
 * Metals & Materials, Services & Utilities.
 */
export const NSE_SECTORS = [
  "Automobile",
  "Banking",
  "Finance",
  "Information Technology",
  "Healthcare",
  "Consumer Goods",
  "Infrastructure & Construction",
  "Energy",
  "Industrial & Goods",
  "Metals & Materials",
  "Services & Utilities",
] as const;

export type NseSector = (typeof NSE_SECTORS)[number];

/** Sector tags for NSE universe symbols — mapped to NSE Nifty groups. */
export const SECTOR_BY_SYMBOL: Record<string, NseSector> = {
  // Automobile — Nifty Auto
  MARUTI: "Automobile",
  "M&M": "Automobile",
  TATAMOTORS: "Automobile",
  EICHERMOT: "Automobile",
  HEROMOTOCO: "Automobile",
  "BAJAJ-AUTO": "Automobile",
  TVSMOTOR: "Automobile",
  MOTHERSON: "Automobile",
  BOSCHLTD: "Automobile",
  MRF: "Automobile",
  BALKRISIND: "Automobile",
  APOLLOTYRE: "Automobile",
  EXIDEIND: "Automobile",
  AMARAJABAT: "Automobile",
  ASHOKLEY: "Automobile",
  ESCORTS: "Automobile",
  TIINDIA: "Automobile",

  // Banking — Nifty Bank / Pvt / PSU Bank
  HDFCBANK: "Banking",
  ICICIBANK: "Banking",
  SBIN: "Banking",
  AXISBANK: "Banking",
  KOTAKBANK: "Banking",
  INDUSINDBK: "Banking",
  BANKBARODA: "Banking",
  PNB: "Banking",
  CANBK: "Banking",
  UNIONBANK: "Banking",
  IDFCFIRSTB: "Banking",
  FEDERALBNK: "Banking",

  // Finance — Nifty Financial Services / NBFC / Insurance
  BAJFINANCE: "Finance",
  BAJAJFINSV: "Finance",
  HDFCLIFE: "Finance",
  SBILIFE: "Finance",
  LICI: "Finance",
  SBICARD: "Finance",
  CHOLAFIN: "Finance",
  MUTHOOTFIN: "Finance",
  MANAPPURAM: "Finance",
  ICICIGI: "Finance",
  ICICIPRULI: "Finance",
  SHRIRAMFIN: "Finance",
  BAJAJHLDNG: "Finance",
  HDFCAMC: "Finance",
  "NAM-INDIA": "Finance",
  ANGELONE: "Finance",
  IIFL: "Finance",
  MOTILALOFS: "Finance",
  BSE: "Finance",
  MCX: "Finance",
  CDSL: "Finance",
  CAMS: "Finance",
  PAYTM: "Finance",
  POLICYBZR: "Finance",
  PFC: "Finance",
  RECLTD: "Finance",
  IRFC: "Finance",

  // Information Technology — Nifty IT
  TCS: "Information Technology",
  INFY: "Information Technology",
  HCLTECH: "Information Technology",
  WIPRO: "Information Technology",
  TECHM: "Information Technology",
  LTIM: "Information Technology",
  PERSISTENT: "Information Technology",
  COFORGE: "Information Technology",
  MPHASIS: "Information Technology",
  OFSS: "Information Technology",

  // Healthcare — Nifty Pharma / Healthcare / Hospitals
  SUNPHARMA: "Healthcare",
  CIPLA: "Healthcare",
  DRREDDY: "Healthcare",
  DIVISLAB: "Healthcare",
  AUROPHARMA: "Healthcare",
  LUPIN: "Healthcare",
  TORNTPHARM: "Healthcare",
  BIOCON: "Healthcare",
  ZYDUSLIFE: "Healthcare",
  ALKEM: "Healthcare",
  LAURUSLABS: "Healthcare",
  GLENMARK: "Healthcare",
  IPCALAB: "Healthcare",
  ABBOTINDIA: "Healthcare",
  SYNGENE: "Healthcare",
  APOLLOHOSP: "Healthcare",
  MAXHEALTH: "Healthcare",
  FORTIS: "Healthcare",
  METROPOLIS: "Healthcare",
  LALPATHLAB: "Healthcare",

  // Consumer Goods — Nifty FMCG / Durables / Retail
  ITC: "Consumer Goods",
  HINDUNILVR: "Consumer Goods",
  NESTLEIND: "Consumer Goods",
  BRITANNIA: "Consumer Goods",
  DABUR: "Consumer Goods",
  MARICO: "Consumer Goods",
  GODREJCP: "Consumer Goods",
  COLPAL: "Consumer Goods",
  TATACONSUM: "Consumer Goods",
  VBL: "Consumer Goods",
  "MCDOWELL-N": "Consumer Goods",
  UBL: "Consumer Goods",
  RADICO: "Consumer Goods",
  TITAN: "Consumer Goods",
  TRENT: "Consumer Goods",
  DMART: "Consumer Goods",
  NYKAA: "Consumer Goods",
  ZOMATO: "Consumer Goods",
  PAGEIND: "Consumer Goods",
  KALYANKJIL: "Consumer Goods",
  ASIANPAINT: "Consumer Goods",
  BERGEPAINT: "Consumer Goods",
  HAVELLS: "Consumer Goods",
  VOLTAS: "Consumer Goods",
  DIXON: "Consumer Goods",
  JUBLFOOD: "Consumer Goods",
  DEVYANI: "Consumer Goods",
  INDHOTEL: "Consumer Goods",
  IHCL: "Consumer Goods",

  // Infrastructure & Construction — Nifty Infra / Construction / Realty
  ADANIPORTS: "Infrastructure & Construction",
  CONCOR: "Infrastructure & Construction",
  IRCTC: "Infrastructure & Construction",
  LT: "Infrastructure & Construction",
  DLF: "Infrastructure & Construction",
  GODREJPROP: "Infrastructure & Construction",
  LODHA: "Infrastructure & Construction",
  INDIGO: "Infrastructure & Construction",
  DELHIVERY: "Infrastructure & Construction",

  // Energy — Nifty Energy / Oil & Gas / Power
  RELIANCE: "Energy",
  ONGC: "Energy",
  BPCL: "Energy",
  IOC: "Energy",
  GAIL: "Energy",
  PETRONET: "Energy",
  IGL: "Energy",
  MGL: "Energy",
  ATGL: "Energy",
  OIL: "Energy",
  NTPC: "Energy",
  POWERGRID: "Energy",
  ADANIPOWER: "Energy",
  TATAPOWER: "Energy",
  TORNTPOWER: "Energy",
  NHPC: "Energy",
  SJVN: "Energy",
  COALINDIA: "Energy",
  ADANIENT: "Energy",

  // Industrial & Goods — Nifty Capital Goods
  SIEMENS: "Industrial & Goods",
  ABB: "Industrial & Goods",
  BEL: "Industrial & Goods",
  HAL: "Industrial & Goods",
  BHEL: "Industrial & Goods",
  CUMMINSIND: "Industrial & Goods",
  POLYCAB: "Industrial & Goods",
  KEI: "Industrial & Goods",
  ASTRAL: "Industrial & Goods",
  SUPREMEIND: "Industrial & Goods",
  MAZDOCK: "Industrial & Goods",
  COCHINSHIP: "Industrial & Goods",
  GRSE: "Industrial & Goods",
  PIDILITIND: "Industrial & Goods",
  SRF: "Industrial & Goods",
  PIIND: "Industrial & Goods",
  DEEPAKNTR: "Industrial & Goods",

  // Metals & Materials — Nifty Metal / Cement / Commodities
  TATASTEEL: "Metals & Materials",
  JSWSTEEL: "Metals & Materials",
  HINDALCO: "Metals & Materials",
  VEDL: "Metals & Materials",
  JINDALSTEL: "Metals & Materials",
  NMDC: "Metals & Materials",
  SAIL: "Metals & Materials",
  NATIONALUM: "Metals & Materials",
  HINDCOPPER: "Metals & Materials",
  ULTRACEMCO: "Metals & Materials",
  GRASIM: "Metals & Materials",
  AMBUJACEM: "Metals & Materials",
  SHREECEM: "Metals & Materials",
  ACC: "Metals & Materials",
  DALBHARAT: "Metals & Materials",
  RAMCOCEM: "Metals & Materials",

  // Services & Utilities — Nifty Media / Telecommunications / Services
  BHARTIARTL: "Services & Utilities",
  NAUKRI: "Services & Utilities",
};

export function getSector(symbol: string): string {
  return SECTOR_BY_SYMBOL[symbol] ?? "Services & Utilities";
}

/** Yahoo symbols for sector / thematic index heat (NSE-aligned labels). */
export const SECTOR_INDEX_QUOTES = [
  { yahoo: "^NSEBANK", name: "Nifty Bank", sector: "Banking" },
  { yahoo: "^CNXIT", name: "Nifty IT", sector: "Information Technology" },
  { yahoo: "^CNXAUTO", name: "Nifty Auto", sector: "Automobile" },
  { yahoo: "^CNXPHARMA", name: "Nifty Pharma", sector: "Healthcare" },
  { yahoo: "^CNXMETAL", name: "Nifty Metal", sector: "Metals & Materials" },
  { yahoo: "^CNXFMCG", name: "Nifty FMCG", sector: "Consumer Goods" },
  { yahoo: "^CNXENERGY", name: "Nifty Energy", sector: "Energy" },
  { yahoo: "^CNXINFRA", name: "Nifty Infra", sector: "Infrastructure & Construction" },
  { yahoo: "^CNXREALTY", name: "Nifty Realty", sector: "Infrastructure & Construction" },
  { yahoo: "NIFTY_FIN_SERVICE.NS", name: "FinNifty", sector: "Finance" },
] as const;
