/**
 * Curated NSE F&O / liquid large-cap universe for Phase 1 scanners.
 * Symbols are real NSE tickers; Yahoo uses the `.NS` suffix.
 */
export const NSE_UNIVERSE: readonly string[] = [
  "RELIANCE",
  "TCS",
  "HDFCBANK",
  "BHARTIARTL",
  "ICICIBANK",
  "INFY",
  "SBIN",
  "ITC",
  "LICI",
  "HINDUNILVR",
  "LT",
  "BAJFINANCE",
  "HCLTECH",
  "MARUTI",
  "SUNPHARMA",
  "AXISBANK",
  "TITAN",
  "NTPC",
  "ULTRACEMCO",
  "ADANIENT",
  "ADANIPORTS",
  "ADANIPOWER",
  "ONGC",
  "POWERGRID",
  "WIPRO",
  "COALINDIA",
  "NESTLEIND",
  "BAJAJFINSV",
  "M&M",
  "TATAMOTORS",
  "TATASTEEL",
  "JSWSTEEL",
  "TECHM",
  "ASIANPAINT",
  "KOTAKBANK",
  "HDFCLIFE",
  "SBILIFE",
  "GRASIM",
  "CIPLA",
  "DRREDDY",
  "DIVISLAB",
  "APOLLOHOSP",
  "EICHERMOT",
  "HEROMOTOCO",
  "BAJAJ-AUTO",
  "INDUSINDBK",
  "BPCL",
  "IOC",
  "HINDALCO",
  "VEDL",
  "JINDALSTEL",
  "DLF",
  "GODREJPROP",
  "LODHA",
  "PIDILITIND",
  "BRITANNIA",
  "DABUR",
  "MARICO",
  "HAVELLS",
  "VOLTAS",
  "SIEMENS",
  "ABB",
  "BEL",
  "HAL",
  "BHEL",
  "IRCTC",
  "IRFC",
  "PFC",
  "RECLTD",
  "BANKBARODA",
  "PNB",
  "CANBK",
  "UNIONBANK",
  "IDFCFIRSTB",
  "FEDERALBNK",
  "AUROPHARMA",
  "LUPIN",
  "TORNTPHARM",
  "BIOCON",
  "ZYDUSLIFE",
  "ALKEM",
  "LAURUSLABS",
  "PERSISTENT",
  "COFORGE",
  "LTIM",
  "MPHASIS",
  "OFSS",
  "TRENT",
  "DMART",
  "NYKAA",
  "ZOMATO",
  "PAYTM",
  "POLICYBZR",
  "SBICARD",
  "CHOLAFIN",
  "MUTHOOTFIN",
  "MANAPPURAM",
  "ICICIGI",
  "ICICIPRULI",
  "SHRIRAMFIN",
  "BAJAJHLDNG",
  "AMBUJACEM",
  "SHREECEM",
  "ACC",
  "DALBHARAT",
  "RAMCOCEM",
  "INDIGO",
  "CONCOR",
  "GAIL",
  "PETRONET",
  "IGL",
  "MGL",
  "ATGL",
  "TATAPOWER",
  "TORNTPOWER",
  "NHPC",
  "SJVN",
  "NMDC",
  "SAIL",
  "NATIONALUM",
  "HINDCOPPER",
  "PIIND",
  "SRF",
  "DEEPAKNTR",
  "NAUKRI",
  "PAGEIND",
  "ABBOTINDIA",
  "GLENMARK",
  "IPCALAB",
  "TVSMOTOR",
  "MOTHERSON",
  "BOSCHLTD",
  "MRF",
  "BALKRISIND",
  "APOLLOTYRE",
  "EXIDEIND",
  "AMARAJABAT",
  "CUMMINSIND",
  "ASHOKLEY",
  "ESCORTS",
  "TIINDIA",
  "POLYCAB",
  "KEI",
  "DIXON",
  "KALYANKJIL",
  "MAXHEALTH",
  "FORTIS",
  "METROPOLIS",
  "LALPATHLAB",
  "SYNGENE",
  "ASTRAL",
  "SUPREMEIND",
  "BERGEPAINT",
  "INDHOTEL",
  "IHCL",
  "JUBLFOOD",
  "DEVYANI",
  "DELHIVERY",
  "MAZDOCK",
  "COCHINSHIP",
  "GRSE",
  "BSE",
  "MCX",
  "CDSL",
  "CAMS",
  "ANGELONE",
  "IIFL",
  "MOTILALOFS",
  "HDFCAMC",
  "NAM-INDIA",
  "UBL",
  "RADICO",
  "COLPAL",
  "GODREJCP",
  "TATACONSUM",
  "VBL",
  "MCDOWELL-N",
] as const;

export function toYahooSymbol(nseSymbol: string): string {
  return `${nseSymbol}.NS`;
}

export function fromYahooSymbol(yahooSymbol: string): string {
  return yahooSymbol.replace(/\.NS$/i, "");
}

export const GLOBAL_TICKER_SYMBOLS = [
  { yahoo: "^GSPC", name: "S&P 500" },
  { yahoo: "^DJI", name: "DOW JONES" },
  { yahoo: "^IXIC", name: "NASDAQ" },
  { yahoo: "^N225", name: "NIKKEI" },
  { yahoo: "^NSEI", name: "NIFTY 50" },
  { yahoo: "^BSESN", name: "SENSEX" },
  { yahoo: "BTC-USD", name: "BTC/USD" },
  { yahoo: "ETH-USD", name: "ETH/USD" },
] as const;
